# -*- coding: utf-8 -*-
"""customerChurnPrediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I8qho7clMOEnpE3uH0S8QbiMh75vUFjj
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

url = "https://raw.githubusercontent.com/tassneam/Credit-Card-Customers-Prediction/main/BankChurners.csv"
df=pd.read_csv(url)
df=df.iloc[:,:-2]
df['Attrition_Flag']=(df['Attrition_Flag']=='Attrited Customer').astype(int)
df=pd.get_dummies(df,drop_first=True)
df.astype(float)

X=df.drop('Attrition_Flag',axis=1).values
y=df['Attrition_Flag'].values

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
x_test=scaler.transform(X_test)

model=Sequential()
model.add(Dense(16,activation='relu',input_dim=33))#hidden layer.
model.add(Dense(1,activation='sigmoid'))#output layer.

model.compile(loss='binary_crossentropy', optimizer='Adam')

model.fit(X_train,y_train,epochs=10)

model.layers[0].get_weights()

X_test=X_test.astype('float64')

y_pred = model.predict(X_test)
for i, pred in enumerate(y_pred):
    if pred > 0.5:
        y_pred[i]=1
    else:
        y_pred[i]=0

accuracy_score(y_test,y_pred)