# -*- coding: utf-8 -*-
"""DigitClassifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tArtVkD2CaGgE73AK75JIn4Fn-bjQFbl
"""

import numpy as np
import pandas as pd
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense,Flatten
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score

(X_train,y_train),(X_test,y_test)=keras.datasets.mnist.load_data()

X_train=X_train/255
X_test=X_test/255

model=Sequential()
model.add(Flatten(input_shape=(28,28)))
model.add(Dense(128,activation='relu'))
model.add(Dense(10,activation='softmax'))

model.summary()

model.compile(loss='sparse_categorical_crossentropy',optimizer='Adam')

model.fit(X_train,y_train,epochs=10,validation_split=0.25)

y_probability=model.predict(X_test)

y_pred=y_probability.argmax(axis=1)

accuracy_score(y_test,y_pred)