# -*- coding: utf-8 -*-
"""pytorch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XkfY6ZbT9LOMvef4-GlyPSi0tPTA0nIy
"""

import torch
print(torch.__version__)

a=torch.empty(2,3) #creating a tensor, empty function allocates memory but doesnt assign any value.
b=torch.ones(2,3)
c=torch.zeros(2,3)
d=torch.rand(2,3)

torch.manual_seed(100) #random hone pe bhi values same rehte hai.
torch.rand(2,3)

x=torch.tensor([[2,3,4],[5,6,7]])

x.dtype

torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

torch.argmax(x)

torch.sigmoid(x)

torch.softmax(x,dtype=torch.float32,dim=0)

torch.relu(x)

m=torch.rand(2,3)
n=torch.rand(2,3)
m+n#creates new tensor.
m.add_(n) #inplace addition.

